"""empty message

Revision ID: 120e45865810
Revises: cd7d4ebe4fa1
Create Date: 2017-03-18 17:46:28.890250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120e45865810'
down_revision = 'cd7d4ebe4fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datacenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datacenters_name'), 'datacenters', ['name'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=False)
    op.create_table('datacenter_server_relationship',
    sa.Column('datacenter_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('datacenter_id', 'server_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datacenter_server_relationship')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_datacenters_name'), table_name='datacenters')
    op.drop_table('datacenters')
    # ### end Alembic commands ###
