"""empty message

Revision ID: e3384e71f811
Revises: 6d2f546d7eec
Create Date: 2017-03-18 16:52:30.403102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3384e71f811'
down_revision = '6d2f546d7eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
